---

apiVersion: v1
kind: Template
metadata:
  name: istio-pod-network-controller
  annotations:
    openshift.io/display-name: Istio Pod Network Controller DeamonSet
    description: Template to create the Istio Pod Network Controller DeamonSet Resources
objects:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
        daemonset: ${NAME}
        application: ${NAME}
    name: ${NAME}
  spec:
    selector:
      matchLabels:
        daemonset: ${NAME}
        application: ${NAME}
    template:
      metadata:
        labels:
          daemonset: ${NAME}
          application: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env:
          - name: ENABLE_INBOUND_IPV6
            value: 'true'        
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: ISTIO_PARAMS
            value: >
              -p 15001 -u 1337 -m REDIRECT -i '*' -x -b 8778, 9779, -d ''              
          args:
          - '-p'
          - '15001'
          - '-u'
          - '1337'
          - '-m'
          - REDIRECT
          - '-i'
          - '*'
          - '-x'
          - ''
          - '-b'
          - '8778, 9779,'
          - '-d'
          - ''      
          image: ${IMAGE}
          imagePullPolicy: Always
          name: ${NAME}
          securityContext:
            privileged: true
          volumeMounts:
          - name: docker
            mountPath: /var/run/docker.sock            
        serviceAccountName: ${SERVICE_ACCOUNT}
        hostPID: true
        volumes:
        - name: docker
          hostPath: 
            path: /var/run/docker.sock
            type: Socket              
    updateStrategy:
      rollingUpdate:
        minReadySeconds: 600
      type: RollingUpdate
parameters:
- name: NAME
  displayName: Name
  description: Name Applied to the Resulting DaemonSet
  value: istio-pod-network-controller
  required: true
- name: IMAGE
  displayName: Image Name
  description: Image Name
  value: istio-pod-network-controller:latest
  required: true
- name: SERVICE_ACCOUNT
  displayName: Service Account
  description: Service Account Name
  value: istio-pod-network-controller
  required: true