---

istio_pod_network_controller_namespace: "istio-system"

openshift_cluster_content:
  - object: projectrequest
    content:
      - name: "Create Project"
        template: "{{ inventory_dir }}/../templates/projectrequest.yml"
        params: "{{ inventory_dir }}/../params/projectrequest"
        template_action: create
  - object: policies
    content:
      - name: "Create SCC"
        template: "{{ inventory_dir }}/../templates/privileged-scc.yml"
        params: "{{ inventory_dir }}/../params/privileged-scc"
      - name: "Create Policies"
        template: "{{ inventory_dir }}/../templates/policies.yml"
        params: "{{ inventory_dir }}/../params/policies"
  - object: builds
    content:
      - name: "Create ImageStream"
        template: "{{ inventory_dir }}/../templates/imagestream-rhel.yml"
        params: "{{ inventory_dir }}/../params/imagestream-rhel"
        namespace: "{{ istio_pod_network_controller_namespace }}"
      - name: "Create Build"
        template: "{{ inventory_dir }}/../templates/istio-pod-network-controller-build.yml"
        params: "{{ inventory_dir }}/../params/istio-pod-network-controller-build"
        namespace: "{{ istio_pod_network_controller_namespace }}"
      - name: "Create DaemonSet"
        template: "{{ inventory_dir }}/../templates/istio-pod-network-controller-daemonset.yml"
        params: "{{ inventory_dir }}/../params/istio-pod-network-controller-daemonset"
        namespace: "{{ istio_pod_network_controller_namespace }}"